Call raise_for_status after retrieving a URL with requests
Sometimes, image files may fail to download due to HTTP errors such as
"429 Too Many Requests".  As a result of the image file on disk being
empty, errors may occur later on in the notebook, which can look
somewhat misleading:

cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:798:
  error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'

Add a call to `raise_for_status()` on the returned `response` object
from the `requests` library, which at the very least notifies the user
that something has gone wrong.

(Alternately, perhaps consider relocating the images from imgur to some
other CDN, or even commit them directly to this repository.)

Also, fix some indentation, spacing, and variable naming
inconsistencies.